FROM ghcr.io/arkime/arkime/arkime:v5-latest

# Vytvoříme skupinu a uživatele, kterého budeme používat pro drop privileges
RUN groupadd -r arkimegroup && \
    useradd -r -g arkimegroup arkimeuser

# Ujistíme se, že adresář pro PCAP soubory je vytvořen a má správná práva
RUN mkdir -p /opt/arkime/raw && chown -R arkimeuser:arkimegroup /opt/arkime/raw

# Spouštíme capture proces, původní entrypoint zůstává
CMD ["/opt/arkime/bin/docker.sh", "capture", "--update-geo"]
